<?php
// icons.php
// A curated list of free Font Awesome 5 icons
return [
    'fa-solid fa-address-book', 'fa-solid fa-address-card', 'fa-solid fa-adjust', 'fa-solid fa-align-center', 'fa-solid fa-align-justify',
    'fa-solid fa-align-left', 'fa-solid fa-align-right', 'fa-solid fa-allergies', 'fa-solid fa-ambulance', 'fa-solid fa-anchor',
    'fa-solid fa-angle-double-down', 'fa-solid fa-angle-double-left', 'fa-solid fa-angle-double-right', 'fa-solid fa-angle-double-up',
    'fa-solid fa-angle-down', 'fa-solid fa-angle-left', 'fa-solid fa-angle-right', 'fa-solid fa-angle-up', 'fa-solid fa-archive',
    'fa-solid fa-arrow-alt-circle-down', 'fa-solid fa-arrow-alt-circle-left', 'fa-solid fa-arrow-alt-circle-right', 'fa-solid fa-arrow-alt-circle-up',
    'fa-solid fa-arrow-down', 'fa-solid fa-arrow-left', 'fa-solid fa-arrow-right', 'fa-solid fa-arrow-up', 'fa-solid fa-arrows-alt',
    'fa-solid fa-arrows-alt-h', 'fa-solid fa-arrows-alt-v', 'fa-solid fa-assistive-listening-systems', 'fa-solid fa-asterisk', 'fa-solid fa-at',
    'fa-solid fa-atlas', 'fa-solid fa-atom', 'fa-solid fa-audio-description', 'fa-solid fa-award', 'fa-solid fa-baby', 'fa-solid fa-baby-carriage',
    'fa-solid fa-backspace', 'fa-solid fa-backward', 'fa-solid fa-balance-scale', 'fa-solid fa-ban', 'fa-solid fa-band-aid', 'fa-solid fa-barcode',
    'fa-solid fa-bars', 'fa-solid fa-baseball-ball', 'fa-solid fa-basketball-ball', 'fa-solid fa-bath', 'fa-solid fa-battery-empty',
    'fa-solid fa-battery-full', 'fa-solid fa-battery-half', 'fa-solid fa-battery-quarter', 'fa-solid fa-battery-three-quarters', 'fa-solid fa-bed',
    'fa-solid fa-beer', 'fa-solid fa-bell', 'fa-solid fa-bell-slash', 'fa-solid fa-bicycle', 'fa-solid fa-binoculars', 'fa-solid fa-birthday-cake',
    'fa-solid fa-blender', 'fa-solid fa-blind', 'fa-solid fa-bold', 'fa-solid fa-bolt', 'fa-solid fa-bomb', 'fa-solid fa-bone', 'fa-solid fa-book',
    'fa-solid fa-book-dead', 'fa-solid fa-book-open', 'fa-solid fa-book-reader', 'fa-solid fa-bookmark', 'fa-solid fa-bowling-ball',
    'fa-solid fa-box', 'fa-solid fa-box-open', 'fa-solid fa-boxes', 'fa-solid fa-braille', 'fa-solid fa-brain', 'fa-solid fa-briefcase',
    'fa-solid fa-briefcase-medical', 'fa-solid fa-broadcast-tower', 'fa-solid fa-broom', 'fa-solid fa-brush', 'fa-solid fa-bug',
    'fa-solid fa-building', 'fa-solid fa-bullhorn', 'fa-solid fa-bullseye', 'fa-solid fa-burn', 'fa-solid fa-bus', 'fa-solid fa-bus-alt',
    'fa-solid fa-calculator', 'fa-solid fa-calendar', 'fa-solid fa-calendar-alt', 'fa-solid fa-calendar-check', 'fa-solid fa-calendar-minus',
    'fa-solid fa-calendar-plus', 'fa-solid fa-calendar-times', 'fa-solid fa-camera', 'fa-solid fa-camera-retro', 'fa-solid fa-capsules',
    'fa-solid fa-car', 'fa-solid fa-car-alt', 'fa-solid fa-car-battery', 'fa-solid fa-car-crash', 'fa-solid fa-car-side', 'fa-solid fa-caret-down',
    'fa-solid fa-caret-left', 'fa-solid fa-caret-right', 'fa-solid fa-caret-up', 'fa-solid fa-cart-arrow-down', 'fa-solid fa-cart-plus',
    'fa-solid fa-certificate', 'fa-solid fa-chalkboard', 'fa-solid fa-chalkboard-teacher', 'fa-solid fa-charging-station', 'fa-solid fa-chart-area',
    'fa-solid fa-chart-bar', 'fa-solid fa-chart-line', 'fa-solid fa-chart-pie', 'fa-solid fa-check', 'fa-solid fa-check-circle',
    'fa-solid fa-check-double', 'fa-solid fa-check-square', 'fa-solid fa-chess', 'fa-solid fa-chevron-circle-down', 'fa-solid fa-chevron-circle-left',
    'fa-solid fa-chevron-circle-right', 'fa-solid fa-chevron-circle-up', 'fa-solid fa-chevron-down', 'fa-solid fa-chevron-left',
    'fa-solid fa-chevron-right', 'fa-solid fa-chevron-up', 'fa-solid fa-child', 'fa-solid fa-church', 'fa-solid fa-circle', 'fa-solid fa-circle-notch',
    'fa-solid fa-clipboard', 'fa-solid fa-clipboard-check', 'fa-solid fa-clipboard-list', 'fa-solid fa-clock', 'fa-solid fa-clone',
    'fa-solid fa-closed-captioning', 'fa-solid fa-cloud', 'fa-solid fa-cloud-download-alt', 'fa-solid fa-cloud-upload-alt', 'fa-solid fa-cocktail',
    'fa-solid fa-code', 'fa-solid fa-code-branch', 'fa-solid fa-coffee', 'fa-solid fa-cog', 'fa-solid fa-cogs', 'fa-solid fa-coins', 'fa-solid fa-columns',
    'fa-solid fa-comment', 'fa-solid fa-comment-alt', 'fa-solid fa-comment-dots', 'fa-solid fa-comment-slash', 'fa-solid fa-comments',
    'fa-solid fa-compact-disc', 'fa-solid fa-compass', 'fa-solid fa-compress', 'fa-solid fa-concierge-bell', 'fa-solid fa-cookie',
    'fa-solid fa-cookie-bite', 'fa-solid fa-copy', 'fa-solid fa-copyright', 'fa-solid fa-couch', 'fa-solid fa-credit-card', 'fa-solid fa-crop',
    'fa-solid fa-crop-alt', 'fa-solid fa-crosshairs', 'fa-solid fa-crow', 'fa-solid fa-crown', 'fa-solid fa-cube', 'fa-solid fa-cubes',
    'fa-solid fa-cut', 'fa-solid fa-database', 'fa-solid fa-deaf', 'fa-solid fa-desktop', 'fa-solid fa-diagnoses', 'fa-solid fa-dice',
    'fa-solid fa-dice-d20', 'fa-solid fa-digital-tachograph', 'fa-solid fa-directions', 'fa-solid fa-divide', 'fa-solid fa-dizzy',
    'fa-solid fa-dna', 'fa-solid fa-dollar-sign', 'fa-solid fa-dolly', 'fa-solid fa-dolly-flatbed', 'fa-solid fa-donate', 'fa-solid fa-door-closed',
    'fa-solid fa-door-open', 'fa-solid fa-dot-circle', 'fa-solid fa-dove', 'fa-solid fa-download', 'fa-solid fa-drafting-compass',
    'fa-solid fa-dragon', 'fa-solid fa-draw-polygon', 'fa-solid fa-drum', 'fa-solid fa-drum-steelpan', 'fa-solid fa-dumbbell',
    'fa-solid fa-edit', 'fa-solid fa-eject', 'fa-solid fa-ellipsis-h', 'fa-solid fa-ellipsis-v', 'fa-solid fa-envelope', 'fa-solid fa-envelope-open',
    'fa-solid fa-envelope-open-text', 'fa-solid fa-envelope-square', 'fa-solid fa-equals', 'fa-solid fa-eraser', 'fa-solid fa-ethernet',
    'fa-solid fa-euro-sign', 'fa-solid fa-exchange-alt', 'fa-solid fa-exclamation', 'fa-solid fa-exclamation-circle', 'fa-solid fa-exclamation-triangle',
    'fa-solid fa-expand', 'fa-solid fa-expand-arrows-alt', 'fa-solid fa-external-link-alt', 'fa-solid fa-external-link-square-alt',
    'fa-solid fa-eye', 'fa-solid fa-eye-dropper', 'fa-solid fa-eye-slash', 'fa-solid fa-fast-backward', 'fa-solid fa-fast-forward',
    'fa-solid fa-fax', 'fa-solid fa-feather', 'fa-solid fa-feather-alt', 'fa-solid fa-female', 'fa-solid fa-fighter-jet', 'fa-solid fa-file',
    'fa-solid fa-file-alt', 'fa-solid fa-file-archive', 'fa-solid fa-file-audio', 'fa-solid fa-file-code', 'fa-solid fa-file-contract',
    'fa-solid fa-file-csv', 'fa-solid fa-file-download', 'fa-solid fa-file-excel', 'fa-solid fa-file-export', 'fa-solid fa-file-image',
    'fa-solid fa-file-import', 'fa-solid fa-file-invoice', 'fa-solid fa-file-invoice-dollar', 'fa-solid fa-file-medical', 'fa-solid fa-file-medical-alt',
    'fa-solid fa-file-pdf', 'fa-solid fa-file-powerpoint', 'fa-solid fa-file-prescription', 'fa-solid fa-file-signature',
    'fa-solid fa-file-upload', 'fa-solid fa-file-video', 'fa-solid fa-file-word', 'fa-solid fa-fill', 'fa-solid fa-fill-drip', 'fa-solid fa-film',
    'fa-solid fa-filter', 'fa-solid fa-fingerprint', 'fa-solid fa-fire', 'fa-solid fa-fire-extinguisher', 'fa-solid fa-first-aid',
    'fa-solid fa-fish', 'fa-solid fa-flag', 'fa-solid fa-flag-checkered', 'fa-solid fa-flask', 'fa-solid fa-folder', 'fa-solid fa-folder-minus',
    'fa-solid fa-folder-open', 'fa-solid fa-folder-plus', 'fa-solid fa-font', 'fa-solid fa-football-ball', 'fa-solid fa-forward',
    'fa-solid fa-frog', 'fa-solid fa-frown', 'fa-solid fa-frown-open', 'fa-solid fa-futbol', 'fa-solid fa-gamepad', 'fa-solid fa-gas-pump',
    'fa-solid fa-gavel', 'fa-solid fa-gem', 'fa-solid fa-genderless', 'fa-solid fa-gift', 'fa-solid fa-gifts', 'fa-solid fa-glass-martini',
    'fa-solid fa-glass-martini-alt', 'fa-solid fa-glasses', 'fa-solid fa-globe', 'fa-solid fa-globe-africa', 'fa-solid fa-globe-americas',
    'fa-solid fa-globe-asia', 'fa-solid fa-golf-ball', 'fa-solid fa-graduation-cap', 'fa-solid fa-greater-than', 'fa-solid fa-greater-than-equal',
    'fa-solid fa-grimace', 'fa-solid fa-grin', 'fa-solid fa-grin-alt', 'fa-solid fa-grin-beam', 'fa-solid fa-grin-beam-sweat', 'fa-solid fa-grin-hearts',
    'fa-solid fa-grin-squint', 'fa-solid fa-grin-squint-tears', 'fa-solid fa-grin-stars', 'fa-solid fa-grin-tears', 'fa-solid fa-grin-tongue',
    'fa-solid fa-grin-tongue-squint', 'fa-solid fa-grin-tongue-wink', 'fa-solid fa-grin-wink', 'fa-solid fa-grip-horizontal',
    'fa-solid fa-grip-vertical', 'fa-solid fa-h-square', 'fa-solid fa-hand-holding', 'fa-solid fa-hand-holding-heart', 'fa-solid fa-hand-holding-usd',
    'fa-solid fa-hand-lizard', 'fa-solid fa-hand-paper', 'fa-solid fa-hand-peace', 'fa-solid fa-hand-point-down', 'fa-solid fa-hand-point-left',
    'fa-solid fa-hand-point-right', 'fa-solid fa-hand-point-up', 'fa-solid fa-hand-pointer', 'fa-solid fa-hand-rock', 'fa-solid fa-hand-scissors',
    'fa-solid fa-hand-spock', 'fa-solid fa-hands', 'fa-solid fa-hands-helping', 'fa-solid fa-handshake', 'fa-solid fa-hashtag', 'fa-solid fa-hdd',
    'fa-solid fa-heading', 'fa-solid fa-headphones', 'fa-solid fa-headphones-alt', 'fa-solid fa-headset', 'fa-solid fa-heart', 'fa-solid fa-heart-broken',
    'fa-solid fa-heartbeat', 'fa-solid fa-helicopter', 'fa-solid fa-highlighter', 'fa-solid fa-history', 'fa-solid fa-hockey-puck',
    'fa-solid fa-home', 'fa-solid fa-hospital', 'fa-solid fa-hospital-alt', 'fa-solid fa-hospital-symbol', 'fa-solid fa-hot-tub',
    'fa-solid fa-hotel', 'fa-solid fa-hourglass', 'fa-solid fa-hourglass-end', 'fa-solid fa-hourglass-half', 'fa-solid fa-hourglass-start',
    'fa-solid fa-i-cursor', 'fa-solid fa-id-badge', 'fa-solid fa-id-card', 'fa-solid fa-id-card-alt', 'fa-solid fa-image', 'fa-solid fa-images',
    'fa-solid fa-inbox', 'fa-solid fa-indent', 'fa-solid fa-industry', 'fa-solid fa-infinity', 'fa-solid fa-info', 'fa-solid fa-info-circle',
    'fa-solid fa-italic', 'fa-solid fa-key', 'fa-solid fa-keyboard', 'fa-solid fa-kiss', 'fa-solid fa-kiss-beam', 'fa-solid fa-kiss-wink-heart',
    'fa-solid fa-kiwi-bird', 'fa-solid fa-language', 'fa-solid fa-laptop', 'fa-solid fa-laptop-code', 'fa-solid fa-laugh', 'fa-solid fa-laugh-beam',
    'fa-solid fa-laugh-squint', 'fa-solid fa-laugh-wink', 'fa-solid fa-layer-group', 'fa-solid fa-leaf', 'fa-solid fa-lemon',
    'fa-solid fa-less-than', 'fa-solid fa-less-than-equal', 'fa-solid fa-level-down-alt', 'fa-solid fa-level-up-alt', 'fa-solid fa-life-ring',
    'fa-solid fa-lightbulb', 'fa-solid fa-link', 'fa-solid fa-lira-sign', 'fa-solid fa-list', 'fa-solid fa-list-alt', 'fa-solid fa-list-ol',
    'fa-solid fa-list-ul', 'fa-solid fa-location-arrow', 'fa-solid fa-lock', 'fa-solid fa-lock-open', 'fa-solid fa-long-arrow-alt-down',
    'fa-solid fa-long-arrow-alt-left', 'fa-solid fa-long-arrow-alt-right', 'fa-solid fa-long-arrow-alt-up', 'fa-solid fa-low-vision',
    'fa-solid fa-magic', 'fa-solid fa-magnet', 'fa-solid fa-male', 'fa-solid fa-map', 'fa-solid fa-map-marked', 'fa-solid fa-map-marked-alt',
    'fa-solid fa-map-marker', 'fa-solid fa-map-marker-alt', 'fa-solid fa-map-pin', 'fa-solid fa-map-signs', 'fa-solid fa-marker',
    'fa-solid fa-mars', 'fa-solid fa-mars-double', 'fa-solid fa-mars-stroke', 'fa-solid fa-mars-stroke-h', 'fa-solid fa-mars-stroke-v',
    'fa-solid fa-medal', 'fa-solid fa-medkit', 'fa-solid fa-meh', 'fa-solid fa-meh-blank', 'fa-solid fa-meh-rolling-eyes', 'fa-solid fa-memory',
    'fa-solid fa-mercury', 'fa-solid fa-microchip', 'fa-solid fa-microphone', 'fa-solid fa-microphone-alt', 'fa-solid fa-microphone-alt-slash',
    'fa-solid fa-microphone-slash', 'fa-solid fa-microscope', 'fa-solid fa-minus', 'fa-solid fa-minus-circle', 'fa-solid fa-minus-square',
    'fa-solid fa-mobile', 'fa-solid fa-mobile-alt', 'fa-solid fa-money-bill', 'fa-solid fa-money-bill-alt', 'fa-solid fa-money-bill-wave',
    'fa-solid fa-money-bill-wave-alt', 'fa-solid fa-money-check', 'fa-solid fa-money-check-alt', 'fa-solid fa-monument', 'fa-solid fa-moon',
    'fa-solid fa-mortar-pestle', 'fa-solid fa-motorcycle', 'fa-solid fa-mouse-pointer', 'fa-solid fa-music', 'fa-solid fa-neuter',
    'fa-solid fa-newspaper', 'fa-solid fa-not-equal', 'fa-solid fa-notes-medical', 'fa-solid fa-object-group', 'fa-solid fa-object-ungroup',
    'fa-solid fa-outdent', 'fa-solid fa-paint-brush', 'fa-solid fa-paint-roller', 'fa-solid fa-palette', 'fa-solid fa-paper-plane',
    'fa-solid fa-paperclip', 'fa-solid fa-parachute-box', 'fa-solid fa-paragraph', 'fa-solid fa-parking', 'fa-solid fa-passport',
    'fa-solid fa-paste', 'fa-solid fa-pause', 'fa-solid fa-pause-circle', 'fa-solid fa-paw', 'fa-solid fa-pen', 'fa-solid fa-pen-alt',
    'fa-solid fa-pen-fancy', 'fa-solid fa-pen-nib', 'fa-solid fa-pen-square', 'fa-solid fa-pencil-alt', 'fa-solid fa-pencil-ruler',
    'fa-solid fa-people-carry', 'fa-solid fa-percent', 'fa-solid fa-percentage', 'fa-solid fa-phone', 'fa-solid fa-phone-slash',
    'fa-solid fa-phone-square', 'fa-solid fa-phone-volume', 'fa-solid fa-piggy-bank', 'fa-solid fa-pills', 'fa-solid fa-plane',
    'fa-solid fa-plane-arrival', 'fa-solid fa-plane-departure', 'fa-solid fa-play', 'fa-solid fa-play-circle', 'fa-solid fa-plug',
    'fa-solid fa-plus', 'fa-solid fa-plus-circle', 'fa-solid fa-plus-square', 'fa-solid fa-podcast', 'fa-solid fa-poll', 'fa-solid fa-poll-h',
    'fa-solid fa-poo', 'fa-solid fa-poop', 'fa-solid fa-portrait', 'fa-solid fa-pound-sign', 'fa-solid fa-power-off', 'fa-solid fa-prescription',
    'fa-solid fa-prescription-bottle', 'fa-solid fa-prescription-bottle-alt', 'fa-solid fa-print', 'fa-solid fa-procedures',
    'fa-solid fa-project-diagram', 'fa-solid fa-puzzle-piece', 'fa-solid fa-qrcode', 'fa-solid fa-question', 'fa-solid fa-question-circle',
    'fa-solid fa-quidditch', 'fa-solid fa-quote-left', 'fa-solid fa-quote-right', 'fa-solid fa-random', 'fa-solid fa-receipt',
    'fa-solid fa-recycle', 'fa-solid fa-redo', 'fa-solid fa-redo-alt', 'fa-solid fa-registered', 'fa-solid fa-reply', 'fa-solid fa-reply-all',
    'fa-solid fa-retweet', 'fa-solid fa-ribbon', 'fa-solid fa-road', 'fa-solid fa-robot', 'fa-solid fa-rocket', 'fa-solid fa-route', 'fa-solid fa-rss',
    'fa-solid fa-rss-square', 'fa-solid fa-ruble-sign', 'fa-solid fa-ruler', 'fa-solid fa-ruler-combined', 'fa-solid fa-ruler-horizontal',
    'fa-solid fa-ruler-vertical', 'fa-solid fa-running', 'fa-solid fa-rupee-sign', 'fa-solid fa-sad-cry', 'fa-solid fa-sad-tear',
    'fa-solid fa-save', 'fa-solid fa-school', 'fa-solid fa-screwdriver', 'fa-solid fa-search', 'fa-solid fa-search-dollar',
    'fa-solid fa-search-location', 'fa-solid fa-search-minus', 'fa-solid fa-search-plus', 'fa-solid fa-seedling', 'fa-solid fa-server',
    'fa-solid fa-shapes', 'fa-solid fa-share', 'fa-solid fa-share-alt', 'fa-solid fa-share-alt-square', 'fa-solid fa-share-square',
    'fa-solid fa-shekel-sign', 'fa-solid fa-shield-alt', 'fa-solid fa-ship', 'fa-solid fa-shipping-fast', 'fa-solid fa-shoe-prints',
    'fa-solid fa-shopping-bag', 'fa-solid fa-shopping-basket', 'fa-solid fa-shopping-cart', 'fa-solid fa-shower', 'fa-solid fa-shuttle-van',
    'fa-solid fa-sign', 'fa-solid fa-sign-in-alt', 'fa-solid fa-sign-language', 'fa-solid fa-sign-out-alt', 'fa-solid fa-signal',
    'fa-solid fa-signature', 'fa-solid fa-sitemap', 'fa-solid fa-skull', 'fa-solid fa-sliders-h', 'fa-solid fa-smile', 'fa-solid fa-smile-beam',
    'fa-solid fa-smile-wink', 'fa-solid fa-smoking', 'fa-solid fa-smoking-ban', 'fa-solid fa-snowflake', 'fa-solid fa-solar-panel',
    'fa-solid fa-sort', 'fa-solid fa-sort-alpha-down', 'fa-solid fa-sort-alpha-up', 'fa-solid fa-sort-amount-down', 'fa-solid fa-sort-amount-up',
    'fa-solid fa-sort-down', 'fa-solid fa-sort-numeric-down', 'fa-solid fa-sort-numeric-up', 'fa-solid fa-sort-up', 'fa-solid fa-space-shuttle',
    'fa-solid fa-spinner', 'fa-solid fa-splotch', 'fa-solid fa-spray-can', 'fa-solid fa-square', 'fa-solid fa-square-full', 'fa-solid fa-stamp',
    'fa-solid fa-star', 'fa-solid fa-star-half', 'fa-solid fa-star-half-alt', 'fa-solid fa-star-of-life', 'fa-solid fa-step-backward',
    'fa-solid fa-step-forward', 'fa-solid fa-stethoscope', 'fa-solid fa-sticky-note', 'fa-solid fa-stop', 'fa-solid fa-stop-circle',
    'fa-solid fa-stopwatch', 'fa-solid fa-store', 'fa-solid fa-store-alt', 'fa-solid fa-stream', 'fa-solid fa-street-view',
    'fa-solid fa-strikethrough', 'fa-solid fa-stroopwafel', 'fa-solid fa-subscript', 'fa-solid fa-subway', 'fa-solid fa-suitcase',
    'fa-solid fa-suitcase-rolling', 'fa-solid fa-sun', 'fa-solid fa-superscript', 'fa-solid fa-surprise', 'fa-solid fa-swatchbook',
    'fa-solid fa-swimmer', 'fa-solid fa-swimming-pool', 'fa-solid fa-sync', 'fa-solid fa-sync-alt', 'fa-solid fa-syringe', 'fa-solid fa-table',
    'fa-solid fa-table-tennis', 'fa-solid fa-tablet', 'fa-solid fa-tablet-alt', 'fa-solid fa-tablets', 'fa-solid fa-tachometer-alt',
    'fa-solid fa-tag', 'fa-solid fa-tags', 'fa-solid fa-tape', 'fa-solid fa-tasks', 'fa-solid fa-taxi', 'fa-solid fa-teeth', 'fa-solid fa-teeth-open',
    'fa-solid fa-terminal', 'fa-solid fa-text-height', 'fa-solid fa-text-width', 'fa-solid fa-th', 'fa-solid fa-th-large', 'fa-solid fa-th-list',
    'fa-solid fa-theater-masks', 'fa-solid fa-thermometer', 'fa-solid fa-thermometer-empty', 'fa-solid fa-thermometer-full',
    'fa-solid fa-thermometer-half', 'fa-solid fa-thermometer-quarter', 'fa-solid fa-thermometer-three-quarters', 'fa-solid fa-thumbs-down',
    'fa-solid fa-thumbs-up', 'fa-solid fa-thumbtack', 'fa-solid fa-ticket-alt', 'fa-solid fa-times', 'fa-solid fa-times-circle',
    'fa-solid fa-tint', 'fa-solid fa-tint-slash', 'fa-solid fa-tired', 'fa-solid fa-toggle-off', 'fa-solid fa-toggle-on', 'fa-solid fa-toilet-paper',
    'fa-solid fa-toolbox', 'fa-solid fa-tools', 'fa-solid fa-tooth', 'fa-solid fa-trademark', 'fa-solid fa-traffic-light', 'fa-solid fa-train',
    'fa-solid fa-transgender', 'fa-solid fa-transgender-alt', 'fa-solid fa-trash', 'fa-solid fa-trash-alt', 'fa-solid fa-tree',
    'fa-solid fa-trophy', 'fa-solid fa-truck', 'fa-solid fa-truck-loading', 'fa-solid fa-truck-monster', 'fa-solid fa-truck-moving',
    'fa-solid fa-truck-pickup', 'fa-solid fa-tshirt', 'fa-solid fa-tty', 'fa-solid fa-tv', 'fa-solid fa-umbrella', 'fa-solid fa-umbrella-beach',
    'fa-solid fa-underline', 'fa-solid fa-undo', 'fa-solid fa-undo-alt', 'fa-solid fa-universal-access', 'fa-solid fa-university',
    'fa-solid fa-unlink', 'fa-solid fa-unlock', 'fa-solid fa-unlock-alt', 'fa-solid fa-upload', 'fa-solid fa-user', 'fa-solid fa-user-alt',
    'fa-solid fa-user-alt-slash', 'fa-solid fa-user-astronaut', 'fa-solid fa-user-check', 'fa-solid fa-user-circle', 'fa-solid fa-user-clock',
    'fa-solid fa-user-cog', 'fa-solid fa-user-edit', 'fa-solid fa-user-friends', 'fa-solid fa-user-graduate', 'fa-solid fa-user-injured',
    'fa-solid fa-user-lock', 'fa-solid fa-user-md', 'fa-solid fa-user-minus', 'fa-solid fa-user-ninja', 'fa-solid fa-user-plus',
    'fa-solid fa-user-secret', 'fa-solid fa-user-shield', 'fa-solid fa-user-slash', 'fa-solid fa-user-tag', 'fa-solid fa-user-tie',
    'fa-solid fa-user-times', 'fa-solid fa-users', 'fa-solid fa-users-cog', 'fa-solid fa-utensil-spoon', 'fa-solid fa-utensils',
    'fa-solid fa-vector-square', 'fa-solid fa-venus', 'fa-solid fa-venus-double', 'fa-solid fa-venus-mars', 'fa-solid fa-vial',
    'fa-solid fa-vials', 'fa-solid fa-video', 'fa-solid fa-video-slash', 'fa-solid fa-volleyball-ball', 'fa-solid fa-volume-down',
    'fa-solid fa-volume-mute', 'fa-solid fa-volume-off', 'fa-solid fa-volume-up', 'fa-solid fa-walking', 'fa-solid fa-wallet',
    'fa-solid fa-warehouse', 'fa-solid fa-weight', 'fa-solid fa-weight-hanging', 'fa-solid fa-wheelchair', 'fa-solid fa-wifi',
    'fa-solid fa-window-close', 'fa-solid fa-window-maximize', 'fa-solid fa-window-minimize', 'fa-solid fa-window-restore',
    'fa-solid fa-wine-glass', 'fa-solid fa-wine-glass-alt', 'fa-solid fa-won-sign', 'fa-solid fa-wrench', 'fa-solid fa-x-ray',
    'fa-solid fa-yen-sign',
    'fa-brands fa-youtube', 'fa-brands fa-facebook', 'fa-brands fa-twitter', 'fa-brands fa-instagram', 'fa-brands fa-pinterest', 'fa-brands fa-linkedin',
    'fa-brands fa-github', 'fa-brands fa-whatsapp', 'fa-brands fa-telegram', 'fa-brands fa-discord', 'fa-brands fa-slack', 'fa-brands fa-dribbble',
];
